name: smotreshka
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-285.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^3.0.0
  json_annotation: ^4.3.0
  blur: ^3.0.0
  json_serializable: ^6.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  formz: ^0.4.1
  animations: ^2.0.2
  
  dart_vlc:
    path: package/dart_vlc


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^3.0.0+1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo/smotreshka_compact_dark.png
    - assets/logo/smotreshka_compact_light.png
    - assets/logo/smotreshka_full_dark.png
    - assets/logo/smotreshka_full_light.png
  fonts:
    - family: Brands
      fonts:
        - asset: assets/fonts/icons/brands.ttf